<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="hello"><a href="#hello">👋 Hello!</a></h2>
    <p>
      I&#39;m Suresh, a Full Stack Web Developer based in Malaysia. I specialize in Magento, WordPress, Shopify,
      Next.js, and Svelte. My blog is dedicated to exploring the fascinating realms of Artificial Intelligence,
      Technology, and Web Development. 🤖💻 Dive into the latest innovations and trends in these dynamic fields with me!
    </p>
    <ImgZoom src="/preview.webp" alt="Suresh's Blog Preview" />
    <ImgZoom src="/mobile-preview.webp" alt="Suresh's Blog Mobile Preview" />

    <h2 id="expertise"><a href="#expertise">🌟 Expertise</a></h2>
    <p>💻 Experienced in Magento, WordPress, Shopify, Next.js, and Svelte.</p>
    <p>🚀 Passionate about crafting fast and efficient web experiences.</p>
    <p>🔍 Dedicated to creating SEO-friendly websites with enhanced performance.</p>
    <p>📱 Skilled in mobile-first and responsive design principles.</p>
    <p>✍️ Proficient in Markdown syntax for content creation.</p>
    <p>📁 Organized approach with folder-based content management.</p>
    <p>🏷️ Knowledgeable in implementing multi-tag filtering for content.</p>
    <p>📄 Capable of generating automatic table of contents for posts.</p>
    <p>⚙️ Able to embed Svelte components and JavaScript within Markdown.</p>
    <p>💬 Familiar with integrating comments systems like Giscus.</p>
    <p>🚀 Capable of deploying websites efficiently on Vercel, Netlify or any other platform including AWS.</p>
    <h2 id="learn-more"><a href="#learn-more">📚 Learn More</a></h2>
    <p>For more details, please refer to my portfolio or reach out via email.</p>
    <h2 id="thank-you"><a href="#thank-you">🙏 Thank You</a></h2>
    <p>Thank you for your interest in my work! Feel free to explore and provide feedback. 😊</p>
    <p>
      Finally, thanks to the amazing work of @kwchang0831, I was able to swiftly build this blog with much less effort
      using the fantastic Svelte-QWER repository. 🙌🌟 Check it out here: <a
        href="https://github.com/kwchang0831/svelte-QWER"
        rel="external">
        https://github.com/kwchang0831/svelte-QWER
      </a>
    </p>
  </article>
</Post>
